# Generated by Django 3.0.8 on 2020-07-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='astroBlog!', max_length=255),
        ),
    ]
